In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import Adam

# Helper libraries
import matplotlib.pyplot as plt
import numpy as np
from os import listdir
from os.path import join
import cv2
import pandas
import os
import random
import pathlib

# Set the path of the input folder

dataset = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
directory = tf.keras.utils.get_file('flower_photos', origin=dataset, untar=True)
data = pathlib.Path(directory)
folders = os.listdir(data)
#print(folders)

# Import the images and resize them to a 128*128 size
# Also generate the corresponding labels

image_names = []
train_labels = []
train_images = []

size = 64,64

for folder in folders:
    for file in os.listdir(os.path.join(data,folder)):
        if file.endswith("jpg"):
            image_names.append(os.path.join(data,folder,file))
            train_labels.append(folder)
            img = cv2.imread(os.path.join(data,folder,file))
            im = cv2.resize(img,size)
            train_images.append(im)
        else:
            continue

# Transform the image array to a numpy type

train = np.array(train_images)
print(train.shape)

# Reduce the RGB values between 0 and 1
train = train.astype('float32') / 255.0
# Extract the labels
label_dummies = pandas.get_dummies(train_labels)
labels =  label_dummies.values.argmax(1)
pandas.unique(train_labels)
print(pandas.unique(labels))

# Shuffle the labels and images randomly for better results

union_list = list(zip(train, labels))
random.shuffle(union_list)
train,labels = zip(*union_list)

# Convert the shuffled list to numpy array type

train = np.array(train)
labels = np.array(labels)


# Develop a sequential model using tensorflow keras
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(64,64,3)),
    keras.layers.Dense(128, activation=tf.nn.tanh),
    keras.layers.Dense(5, activation=tf.nn.softmax)
])

# Compute the model parameters

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train,labels, epochs=5)



228813984/228813984 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step
(0,)


ValueError: attempt to get argmax of an empty sequence

In [ ]:
# Model Inference
# Preprocess the sample image
img_height = 64
img_width = 64
import cv2
#image = cv2.imread('/root/.keras/datasets/flower_photos/roses/10090824183_d02c613f10_m.jpg')
#image = cv2.imread('/root/.keras/datasets/flower_photos/tulips/100930342_92e8746431_n.jpg')
image = cv2.imread('/root/.keras/datasets/flower_photos/sunflowers/1008566138_6927679c8a.jpg')
# print(image)
image_resized = cv2.resize(image, (img_height, img_width))
image = np.expand_dims(image_resized, axis=0)

print(image)
print(image.shape)

# Make predictions
image_pred = model.predict(image)

print(image_pred)
# Produce a human-readable output label\
classes_labels = pandas.unique(train_labels)


image_output_class = classes_labels[np.argmax(image_pred)]
print(classes_labels)
print(np.argmax(image_pred))

print("The predicted class is", image_output_class)


[[[[ 38  50  30]
   [ 36  50  29]
   [ 30  42  22]
   ...
   [ 13  32  11]
   [ 16  37  16]
   [ 19  48  24]]

  [[ 29  46  23]
   [ 27  45  23]
   [ 20  35  17]
   ...
   [ 18  51  24]
   [ 24  59  29]
   [ 20  63  29]]

  [[ 28  49  25]
   [ 19  44  19]
   [ 15  32  12]
   ...
   [ 30  88  59]
   [ 30  72  40]
   [ 21  57  27]]

  ...

  [[ 43 115  83]
   [ 23  78  45]
   [ 28  73  40]
   ...
   [ 25  80  48]
   [ 58 104  60]
   [ 69 110  66]]

  [[ 46 117  79]
   [ 12  73  34]
   [ 24  55  41]
   ...
   [ 29  82  45]
   [ 67 108  73]
   [ 47 103  52]]

  [[ 34 106  74]
   [ 17  74  39]
   [ 26  51  39]
   ...
   [ 34  87  42]
   [ 49 100  49]
   [ 48  95  45]]]]
(1, 64, 64, 3)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.06130545 0.20434576 0.0701401  0.47468764 0.18952104]]
['roses' 'dandelion' 'tulips' 'sunflowers' 'daisy']
3
The predicted class is sunflowers


<ipython-input-50-10e56d04d513>:21: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  classes_labels = pandas.unique(train_labels)


In [ ]:
!sudo apt-get update


Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:4 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:5 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:6 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [45.2 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,439 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,223 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3,298 kB]
Get:13 https:/

In [ ]:
!sudo apt-get install ca-certificates curl


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
The following additional packages will be installed:
  libcurl4 libcurl4-openssl-dev
Suggested packages:
  libcurl4-doc libidn11-dev libldap2-dev librtmp-dev
The following packages will be upgraded:
  curl libcurl4 libcurl4-openssl-dev
3 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
Need to get 868 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.19 [386 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.19 [194 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.19 [289 kB]
Fetched 868 kB in 1s (1,132 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-lik

In [ ]:
!sudo apt-get update
!sudo apt-get install ca-certificates curl
!sudo install -m 0755 -d /etc/apt/keyrings
!sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
!sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
!echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
!sudo apt-get update
!sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
!sudo docker run hello-world


Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:6 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:11 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Readin

In [ ]:
!docker --version

Docker version 27.3.1, build ce12230


In [ ]:
!docker pull tensorflow/serving

Using default tag: latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
